### ISSUE TITLE
Navbar Toggler Icon is misplaced

### ISSUE THREAD

**Issue by iSumitBanik** [sagarbanik11/covidnews#1]
The Navbar toggler icon is misplaced. It's breaking the UI of the web app. 
Please look into the issue.

The screenshot is attached below. 

![image](https://user-images.githubusercontent.com/36637433/78907936-ff9b2300-7a9e-11ea-9df6-3a3a7ca09b15.png)

**Comment by sagarbanik11** [comment]
Updated
